### ISSUE TITLE
报错：subPackage.pages is not iterable

### ISSUE THREAD

**Issue by chenxs1427** [r3x5ur/wxapkg-unpacker#4]
好像是因为微信的小程序架构升级了

**Comment by r3x5ur** [comment]
> 好像是因为微信的小程序架构升级了

提供下详细的信息

**Comment by r3x5ur** [comment]
> 好像是因为微信的小程序架构升级了

拉取最新代码，已经更新

**Comment by chen1sheng** [comment]
貌似还是没用解决呀最新代码还是会有这种报错
TypeError: subPackage.pages is not iterable

测试用的包：
https://res.servicewechat.com/weapp/release_encrypt/66_mQ2TCACaPCJD_9aWsfroxi2zaqfRVntb0_J8kd6g0LzJTZtnu7pyfV2iKjWAh5CYhZ68jabtUj-IpQEd.zstd?rand=1845768714&pass_key=2BZ0rc3mF7VNPXRt3SVYHmpUc9ahZCwWd5n_wIVshYDsUTaG3WVrzGGihqefOl9TUz360e9WoAcG4u57ON1o01Yjvg-xxpBK_MXta97VzgENpZMgCr7V9YGp3jZejJsGZModTrqPpNmfoQC5Ok5tt-oc9XUkEERTZwRnt-HvH41BRs-fxRSg_pVKfb39LLYlxlsKcl10qjRvslZw3O_X3clX6ljmk1OwLInwb_1KMU0~

**Comment by Epxir** [comment]
subPackage.pages is not iterable 
[Uploading 1.zip…]()

**Comment by chen1sheng** [comment]
再看了下是因为subPackage里面pages为空触发的报错，加了个try解决了，但是又有一堆静态资源报错QAQ 有分包的还原好难啊

**Comment by Epxir** [comment]
subPackage.pages is not iterable
<img width="561" alt="image" src="https://user-images.githubusercontent.com/79371047/224937045-3c037d1d-0aaa-4b73-a0f5-6aeb85d9d8ed.png">
[1.zip](https://github.com/r3x5ur/wxapkg-unpacker/files/10966014/1.zip)

**Comment by liuyu2018** [comment]
> 再看了下是因为subPackage里面pages为空触发的报错，加了个try解决了，但是又有一堆静态资源报错QAQ 有分包的还原好难啊

同感...我加了个判断绕过了这个报错，但是后台调试的时候又发现生成的代码格式有问题，解析语法树不行了......
