### ISSUE TITLE
在还原wxml时报错, vm.js在运行js代码时抛出`SyntaxError: Unexpected token '}'`异常

### ISSUE THREAD

**Issue by ciaoly** [r3x5ur/wxapkg-unpacker#6]
**Describe the bug**
在还原wxml时报错: `SyntaxError: Unexpected token '}'`, vm运行js代码时发生语法错误

**复现步骤**

```cmd
wxunpacker.cmd .\_468736192_311.wxapkg -f
```

**Actual behavior**/**实际结果**

```cmd
~\AppData\Local\Yarn\Data\global\node_modules\vm2\lib\transformer.js:86
                throw e;
                ^

vm.js:21
}
^

SyntaxError: Unexpected token '}'
    at makeNiceSyntaxError (~\AppData\Local\Yarn\Data\global\node_modules\vm2\lib\transformer.js:41:16)
    at transformer (~\AppData\Local\Yarn\Data\global\node_modules\vm2\lib\transformer.js:84:8)
    at VM.run (~\AppData\Local\Yarn\Data\global\node_modules\vm2\lib\vm.js:491:16)
    at ~\AppData\Local\Yarn\Data\global\node_modules\wxapkg-unpacker\packages\unpacker\src\wuWxml.js:464:10
    at ~\AppData\Local\Yarn\Data\global\node_modules\wxapkg-unpacker\packages\unpacker\src\wuRestoreZ.js:291:23
    at catchZ (~\AppData\Local\Yarn\Data\global\node_modules\wxapkg-unpacker\packages\unpacker\src\wuRestoreZ.js:33:3)
    at getZ (~\AppData\Local\Yarn\Data\global\node_modules\wxapkg-unpacker\packages\unpacker\src\wuRestoreZ.js:291:5)
    at ~\AppData\Local\Yarn\Data\global\node_modules\wxapkg-unpacker\packages\unpacker\src\wuWxml.js:438:5 
    at ~\AppData\Local\Yarn\Data\global\node_modules\wxapkg-unpacker\packages\unpacker\src\wuLib.js:105:10 
    at agent (~\AppData\Local\Yarn\Data\global\node_modules\wxapkg-unpacker\packages\unpacker\src\wuLib.js:66:17)

Node.js v18.14.2
```

**运行环境、版本信息**<br/>
**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - NodeJS: 18.14.2
 - Version: version v1.0.1

**Additional context**/**其他描述**

```js
global.__wcc_version__='v0.5vv_20200413_syb_scopedata'
```

出现这个问题应该是因为微信小程序的编译方法发生了变化. 使用`wxappUnpacker`反编译同一个wxpkg也是报相同的错误. 解决此bug可能需要重新分析小程序的`$gwx`函数?

[附加该小程序样品](https://www.swisstransfer.com/d/3dba4e25-ba15-4926-8e46-6067e0fd5c4a), *链接30天有效*

**Comment by r3x5ur** [comment]
@ciaoly 感谢提交，正在解决中

**Comment by Haojinlong555** [comment]
+1求大佬解决

**Comment by ciaoly** [comment]
> @ciaoly 感谢提交，正在解决中
解包这个小程序后, 多了个*appservice.app.js*. 不知道是不是因为这个原因?

**Comment by ccfleaf** [comment]
+1也是这个问题SyntaxError: Unexpected token '}'

**Comment by r3x5ur** [comment]
努力撸代码中 新版已经能检测出各种版本的包了~  敬请期待咯
![image](https://user-images.githubusercontent.com/64947085/223902404-406437c2-a428-493b-bee6-4c1c9ce08893.png)

**Comment by r3x5ur** [comment]
> 

现在发现有好几种打包方式， 这种应该是最新版的 我称为 `APP_V3`

**Comment by ccfleaf** [comment]
大佬加油！

r3x5ur ***@***.***> 于2023年3月9日周四 10:46写道：

**Comment by ciaoly** [comment]
这两天我看了看那个样品小程序包，它的wxml编译后的js和原来的不同之处有两个：

1. `gz$gwx`函数的命名变了。以前是`gz$gwxc`，现在是`gz$gwx1_XC_1_0_1`这样子
2. `m`函数的命名和组织形式变了。以前是所有的`m`函数都放在了一起、依次声明为`m0, m1, m2`这样子，并且依赖的组件库声明和导入也放在了一起；现在是每一个`Z`数组后面都紧跟着一个`m0`函数，依赖库使用`define`和`require`两函数导入。

我简单修改了一下 *[wuWxml.js](https://gist.github.com/ciaoly/1d166c087455d65596a4b1817e7bccd5)* 和 *[wuRestoreZ.js](https://gist.github.com/ciaoly/4abbbf72f61d6599fbbac7cfbe04ba2c)* 文件，成功反编译出相关的Page代码。还有wxss代码部分，我就简单粗暴的手写了一个[`setCssToHead`函数](https://gist.github.com/ciaoly/85e4a7b74e3493c95b35db4ac643efb6)，把数组里面的字符串拼接了一下。目前来看，能用.

以上内容供大佬参考。

**Comment by stellarding** [comment]
> 这两天我看了看那个样品小程序包，它的wxml编译后的js和原来的不同之处有两个：
> 
> 1. `gz$gwx`函数的命名变了。以前是`gz$gwx1`，现在是`gz$gwx1_XC_1_0_1`这样子
> 2. `m`函数的命名和组织形式变了。以前是所有的`m`函数都放在了一起、依次声明为`m0, m1, m2`这样子；现在是每一个`Z`数组后面都紧跟着一个`m0`函数。
> 
> 我简单修改了一下 _[wuWxml.js](https://gist.github.com/ciaoly/1d166c087455d65596a4b1817e7bccd5)_ 和 _[wuRestoreZ.js](https://gist.github.com/ciaoly/4abbbf72f61d6599fbbac7cfbe04ba2c)_ 文件，成功反编译出相关的Page代码。还有wxss代码部分，我就简单粗暴的手写了一个[`setCssToHead`函数](https://gist.github.com/ciaoly/85e4a7b74e3493c95b35db4ac643efb6)，把数组里面的字符串拼接了一下。目前来看，能用.
> 
> 以上内容供大佬参考。

setCssToHead这个函数怎么使用？

**Comment by ciaoly** [comment]
> > 这两天我看了看那个样品小程序包，它的wxml编译后的js和原来的不同之处有两个：
> > 
> > 1. `gz$gwx`函数的命名变了。以前是`gz$gwx1`，现在是`gz$gwx1_XC_1_0_1`这样子
> > 2. `m`函数的命名和组织形式变了。以前是所有的`m`函数都放在了一起、依次声明为`m0, m1, m2`这样子；现在是每一个`Z`数组后面都紧跟着一个`m0`函数。
> > 
> > 我简单修改了一下 _[wuWxml.js](https://gist.github.com/ciaoly/1d166c087455d65596a4b1817e7bccd5)_ 和 _[wuRestoreZ.js](https://gist.github.com/ciaoly/4abbbf72f61d6599fbbac7cfbe04ba2c)_ 文件，成功反编译出相关的Page代码。还有wxss代码部分，我就简单粗暴的手写了一个[`setCssToHead`函数](https://gist.github.com/ciaoly/85e4a7b74e3493c95b35db4ac643efb6)，把数组里面的字符串拼接了一下。目前来看，能用.
> > 以上内容供大佬参考。
> 
> setCssToHead这个函数怎么使用？

打开浏览器的控制台, 先把我*gist*里面的`setCssToHead`粘贴执行, 再粘贴执行这一段函数就好了:

![oKTzF.png](https://i.328888.xyz/2023/03/10/oKTzF.png)

**Comment by r3x5ur** [comment]
#15

**Comment by orkunzozturk** [comment]
+1也是这个问题SyntaxError: Unexpected token '}'
